remote_manager/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('login', views.MainLoginView.as_view(), name='login'),
    path('logout', views.MainLogoutView.as_view(), name='logout'),
    path('change_password', views.PasswordUpdateView.as_view(), name='change_password'),
    path('user/list', views.UserListView.as_view(), name='user_list'),
    path('user/create', views.UserCreateView.as_view(), name='user_create'),
    path('user/update/<str:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('user/detail/<str:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('org/list', views.OrgListView.as_view(), name='org_list'),
    path('org/create', views.OrgCreateView.as_view(), name='org_create'),
    path('org/update/<str:pk>', views.OrgUpdateView.as_view(), name='org_update'),
    path('org/detail/<str:pk>', views.OrgDetailView.as_view(), name='org_detail')
]

remote_manager/novnc_console/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list', views.VNCListView.as_view(), name='vnc_list'),
    path('create', views.VNCCreateView.as_view(), name='vnc_create'),
    path('detail/<str:pk>', views.VNCDetailView.as_view(), name='vnc_detail'),
    path('update/<str:pk>', views.VNCUpdateView.as_view(), name='vnc_update'),
    path('vnc_console/<str:pk>', views.VNCConsoleView.as_view(), name='vnc_console'),
    path('vnc_playback/<str:pk>', views.VNCPlaybackView.as_view(), name='vnc_playback'),

]

remote_manager/remote_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vnc/', include('novnc_console.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

remote_manager/novnc_console/models.py
from django.db import models
from uuid import uuid4
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from main.models import Organization

# Create your models here.
class VNCSession(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        editable=False
    )

    name = models.CharField(
        max_length=100,
        unique=True
    )

    ip4_addr = models.GenericIPAddressField(
        protocol='IPv4'
    )

    vnc_display = models.IntegerField(
        validators=[MaxValueValidator(10), MinValueValidator(1)]
    )

    password = models.CharField(
        max_length=50
    )

    organizations = models.ManyToManyField(
        Organization
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name='vnc_created_by'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
    )

    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name='vnc_updated_by')

    updated_at = models.DateTimeField(
        auto_now=True,
        null=True
    )

    def __str__(self):
        return self.name

remote_manager/novnc_console/forms.py
from django import forms
from .models import VNCSession
from main.models import Organization

class VNCSessionForm(forms.ModelForm):
    class Meta:
        model = VNCSession
        fields = ('name', 'ip4_addr', 'vnc_display', 'password', 'organizations')
        widgets = {
            'name': forms.TextInput(),
            'ip4_addr': forms.TextInput(),
            'vnc_display': forms.TextInput(),
            'password': forms.PasswordInput()
        }

    organizations = forms.ModelMultipleChoiceField(queryset=Organization.objects.all())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if VNCSession.objects.filter(id=self.instance.id):
            self.instance.updated_by = self.request.user
        else:
            self.instance.created_by = self.request.user
        return super().save(commit=commit)

remote_manager/novnc_console/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views import View
from django.conf import settings
from .models import VNCSession
from .forms import VNCSessionForm
from secrets import token_hex
from datetime import datetime
import os
from threading import Timer

# Create your views here.
class PassRequestToFormViewMixin:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class VNCListView(LoginRequiredMixin, ListView):
    queryset = VNCSession.objects.all()
    template_name = 'novnc_console/vnc_list.html'


class VNCCreateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, CreateView):
    form_class = VNCSessionForm
    template_name = 'novnc_console/vnc_form.html'
    success_url = reverse_lazy('vnc_list')
    def test_func(self):
        return self.request.user.is_staff


class VNCUpdateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, UpdateView):
    model = VNCSession
    form_class = VNCSessionForm
    template_name = 'novnc_console/vnc_form.html'
    def get_success_url(self):
        return reverse_lazy('vnc_detail', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        return self.request.user.is_staff


class VNCDetailView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = VNCSession
    template_name = 'novnc_console/vnc_detail.html'
    success_url = reverse_lazy('vnc_list')
    def test_func(self):
        return self.request.user.is_staff


class VNCPlaybackView(LoginRequiredMixin, UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        name = VNCSession.objects.get(pk=pk).name
        record_root = 'media/record/' + pk
        record_by_user = {}
        for root, dirs, files in os.walk(record_root):
            for d in dirs:
                record_by_user[d] = []
        for user in record_by_user.keys():
            for root, dirs, files in os.walk(record_root + '/' + user):
                record_by_user[user] = files
        context = {'pk': pk, 'name': name, 'record_by_user': record_by_user}
        return render(request, 'novnc_console/vnc_playback.html', context)

    def test_func(self):
        return self.request.user.is_staff


class VNCConsoleView(LoginRequiredMixin, UserPassesTestMixin, View):
    def set_token(self, token):
        f = open('token/token.conf', 'a')
        f.write(token)
        f.close()

    def unset_token(self, token):
        f = open('token/token.conf', 'r')
        token_new = ''
        for line in f:
            if line != line:
                token += line
        f = open('token/token.conf', 'w')
        f.write(token_new)


    def logging_user(self):
        param = (self.request.user.username, datetime.now(), self.vnc.name, self.vnc.ip4_addr, self.vnc.vnc_display)
        message ='user[%s] %s connecting to:%s[%s:%s]\n' % param
        logfile = open('log/user.log', 'a')
        logfile.write(message)

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        token = token_hex(16)
        proxy_ip, proxy_port = settings.WEBSOCKIFY
        vnc_ip = self.vnc.ip4_addr
        vnc_port = 5900 + int(self.vnc.vnc_display)
        password = self.vnc.password
        context = {'pk': pk, 'proxy_ip': proxy_ip, 'proxy_port': proxy_port, 'token': token, 'password': password}
        token = '%s: %s:%i\n' % (token, vnc_ip, vnc_port)
        self.set_token(token)
        self.logging_user()
        Timer(10, self.unset_token, [token]).start()
        return render(request, 'novnc_console/vnc_console.html', context)

    def test_func(self):
        self.vnc = VNCSession.objects.get(id=self.kwargs['pk'])
        return self.request.user.is_staff or self.request.user.organization in self.vnc.organizations.all()

remote_manager/novnc_console/templates/novnc_console/vnc_console.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">noVNC</h1>
    </div>

    <div>
         <iframe width="100%" height="480" src="/static/noVNC/vnc_lite.html?host={{ proxy_ip }}&port={{ proxy_port }}&password={{ password }}&path=websockify/?token={{ token }}" title=""></iframe>
    </div>

    <script>

        const recordingSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/{{ pk }}/'
        )


        const checkWS = setInterval(
            () => {
                if (recordingSocket.readyState === WebSocket.CLOSED) {
                    location.replace('{% url 'vnc_list' %}')
                }
            }, 1000)
    </script>

{% endblock %}

remote_manager/novnc_console/templates/novnc_console/vnc_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">VNC Detail</h1>
    </div>

    <div>
        <div class="my-2 text-right">
            <div class="btn-group">
                <a href="{% url 'vnc_update' vncsession.id %}" class="btn btn-primary" aria-current="page">Edit</a>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-4">
                    Name
                </div>
                <div class="col-8">
                    {{ vncsession.name }}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    IP Address
                </div>
                <div class="col-8">
                    {{ vncsession.ip4_addr }}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    Display
                </div>
                <div class="col-8">
                    {{ vncsession.vnc_display }}
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    Organizations
                </div>
                <div class="col-8">
                    {% for org in vncsession.organizations.all %}
                        {{ org }},
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Created by
                </div>
                <div class="col-8">
                    {{ vncsession.created_by }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Created at
                </div>
                <div class="col-8">
                    {{ vncsession.created_at }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Updated by
                </div>
                <div class="col-8">
                    {{ vncsession.updated_by }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Updated at
                </div>
                <div class="col-8">
                    {{ vncsession.updated_at }}
                </div>
            </div>
        </div>
    </div>



    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
                </div>
                <div class="modal-body">
                    Delete <b>{{ vncsession.name }}</b>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" >Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

remote_manager/novnc_console/templates/novnc_console/vnc_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {% if request.path == '/vnc/create' %}
        <h1 class="h2">Add VNC</h1>
        {% else %}
        <h1 class="h2">Edit VNC</h1>
        {% endif %}
    </div>

    <div>
        <div>
            <form class="uniForm" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.name | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.ip4_addr | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.vnc_display | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.organizations | as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

remote_manager/novnc_console/templates/novnc_console/vnc_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">VNC List</h1>
    </div>

    <div>
        {% if request.user.is_staff %}
        <div class="my-2 text-right">
            <a type="button" class="btn btn-primary" href="{% url 'vnc_create' %}">Add</a>
        </div>
        {% endif %}

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">IP address</th>
                    <th scope="col">Display</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for vnc in vncsession_list %}
                <tr>
                    <th scope="row">{{ vnc.name }}</th>
                    <td>{{ vnc.ip4_addr }}</td>
                    <td>:{{ vnc.vnc_display }}</td>
                    <td>
                        {% if request.user.is_staff %}
                        <a href="{% url 'vnc_detail' vnc.id %}" class="btn btn-primary btn-sm" aria-current="page">Detail</a>
                        {% endif %}
                        {% if request.user.is_staff or request.user.organization in vnc.organizations.all %}
                        <a href="{% url 'vnc_console' vnc.id %}" class="btn btn-warning text-light btn-sm" aria-current="page">Console</a>
                        <a href="{% url 'vnc_playback' vnc.id %}" class="btn btn-secondary text-light btn-sm" aria-current="page">Playback</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

remote_manager/novnc_console/templates/novnc_console/vnc_playback.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Playback - {{ name }}</h1>
    </div>

    <div>
        <div class="row">
            <div class="col-12 col-md-8">
                <video width="100%" height="360" controls>
                    Your browser does not support the video tag.
                </video>
            </div>

            <div class="col-12 col-md-4">
                <ul class="list-group">
                    {% for key, value in record_by_user.items %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a class="card-link" data-toggle="collapse" data-target="#colapse{{ key }}">{{ key }}</a>
                    <span class="badge bg-primary rounded-pill text-white">{{ value|length}}</span>
                    </li>
                    <div class="collapse" id="colapse{{ key }}">
                        <ul class="list-group">
                            {% for record in value %}
                            <li onclick="changeSource('{{ user }}/{{ record }}')" class="list-group-item">{{ record }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>



    <script>
        function changeSource (record) {
            var video = $('video')[0];
            var source = document.createElement('source');
            source.setAttribute('src', '/media/record/' + '{{ pk }}' + '/' + record);
            video.appendChild(source);
            video.play();
        }

    </script>

{% endblock %}