remote_manager/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('login', views.MainLoginView.as_view(), name='login'),
    path('logout', views.MainLogoutView.as_view(), name='logout'),
    path('change_password', views.PasswordUpdateView.as_view(), name='change_password'),
    path('user/list', views.UserListView.as_view(), name='user_list'),
    path('user/create', views.UserCreateView.as_view(), name='user_create'),
    path('user/update/<str:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('user/detail/<str:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('org/list', views.OrgListView.as_view(), name='org_list'),
    path('org/create', views.OrgCreateView.as_view(), name='org_create'),
    path('org/update/<str:pk>', views.OrgUpdateView.as_view(), name='org_update'),
    path('org/detail/<str:pk>', views.OrgDetailView.as_view(), name='org_detail')
]

remote_manager/remote_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vnc/', include('novnc_console.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

remote_manager/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class Organization(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_created_by'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
    )

    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='group_updated_by'
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        null=True
    )

    def __str__(self):
        return self.name



class CustomUser(AbstractUser):
    organization = models.ForeignKey(
        Organization,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    is_active = models.BooleanField(
        default=True,
    )

    is_staff = models.BooleanField(
        default=False,
    )

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name='user_created_by'
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='user_updated_by'

    )

    updated_at = models.DateTimeField(
        auto_now=True,
        null=True
    )

    def __str__(self):
        return self.username

remote_manager/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from .models import CustomUser, Organization

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'organization', 'is_staff', 'is_active')
        widgets = {
            'username': forms.TextInput(),
            'is_staff': forms.CheckboxInput(),
            'is_active': forms.CheckboxInput()
        }

    organization = forms.ModelChoiceField(queryset=Organization.objects.all())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if CustomUser.objects.filter(id=self.instance.id):
            self.instance.updated_by = self.request.user
        else:
            self.instance.created_by = self.request.user
        return super().save(commit=commit)


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('name',)
        widgets = {
            'name': forms.TextInput()
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        if Organization.objects.filter(id=self.instance.id):
            self.instance.updated_by = self.request.user
        else:
            self.instance.created_by = self.request.user
        return super().save(commit=commit)

remote_manager/main/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import CustomUser, Organization
from .forms import CustomUserCreationForm, OrganizationForm
import re


# Create your views here.
class PassRequestToFormViewMixin:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class MainLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'main/login.html'


class MainLogoutView(LogoutView, LoginRequiredMixin):
    pass


class PasswordUpdateView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    model = CustomUser
    form_class = PasswordChangeForm
    template_name = 'main/password.html'
    success_message = 'Success!'

    def get_success_url(self):
        return reverse_lazy('profile')


class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        # read websockify log
        logfile = open('log/websockify.log', 'r')
        log = logfile.readlines()
        logfile.close()
        if len(log) >= 30:
            log = log[-30:]
        conn_log = []
        for line in log:
            conn = re.match(r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}.+\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,4})\n', line)
            if conn:
                conn_log += [conn.group(1)]

        # read app novnc_console log
        user_logfile = open('log/user.log', 'r')
        user_log = user_logfile.readlines()
        user_logfile.close()

        user_list = []
        host_list = []

        for line in user_log:
            a = re.match(r'user\[(.+)\] .+connecting to:.+\[(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):\d+\]\n', line)
            user_list += [a.group(1)]
            host_list += [a.group(2)]

        user_count = []
        for user in set(user_list):
            user_count += [[user, user_list.count(user)]]

        host_count = []
        for host in set(host_list):
            host_count += [[host, host_list.count(host)]]

        if len(user_log) > 10:
            user_log = user_log[-10:]

        context = {'conn_log': conn_log, 'user_log': user_log, 'host_count': host_count, 'user_count': user_count}
        return render(request, 'main/dashboard.html', context)


class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    queryset = CustomUser.objects.filter(is_superuser=False)
    template_name = 'main/user_list.html'

    def test_func(self):
        return self.request.user.is_staff


class UserCreateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, CreateView):
    form_class = CustomUserCreationForm
    template_name = 'main/user_form.html'
    success_url = reverse_lazy('user_list')

    def test_func(self):
        return self.request.user.is_staff


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'main/user_form.html'

    def get_success_url(self):
        return reverse_lazy('user_detail', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        return self.request.user.is_staff


class UserDetailView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CustomUser
    template_name = 'main/user_detail.html'
    success_url = reverse_lazy('user_list')

    def test_func(self):
        return self.request.user.is_staff


class OrgListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Organization
    template_name = 'main/org_list.html'

    def test_func(self):
        return self.request.user.is_staff


class OrgCreateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, CreateView):
    form_class = OrganizationForm
    template_name = 'main/org_form.html'
    success_url = reverse_lazy('org_list')

    def test_func(self):
        return self.request.user.is_staff


class OrgUpdateView(LoginRequiredMixin, UserPassesTestMixin, PassRequestToFormViewMixin, UpdateView):
    model = Organization
    form_class = OrganizationForm
    template_name = 'main/org_form.html'

    def get_success_url(self):
        return reverse_lazy('org_detail', kwargs={'pk': self.kwargs['pk']})

    def test_func(self):
        return self.request.user.is_staff


class OrgDetailView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Organization
    template_name = 'main/org_detail.html'
    success_url = reverse_lazy('org_list')

    def test_func(self):
        return self.request.user.is_staff

remote_manager/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Remote Managerβ</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <style>
        .fa {
            width: 18px;
            text-align: center;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark  ">
        <a class="navbar-brand " href="/">Remote Manager(β)</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul></ul>
            <ul class="navbar-nav px-3 mr-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="far fa-user" aria-hidden="true"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right bg-dark" aria-labelledby="navbarDropdown">
                        <a class="nav-link" href="{% url 'change_password' %}">Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>


    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse" style="height:100%; position: fixed;">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'dashboard' %}">
                                <i class="fa fa-tachometer-alt"></i>
                                Dashboard
                            </a>
                        </li>
                    </ul>


                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Remote Console</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'vnc_list' %}">
                                <i class="fa fa-desktop"></i>
                                VNC
                            </a>
                        </li>
                    </ul>
                    {% if request.user.is_staff %}
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Management</span>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_list' %}">
                                <i class="fa fa-user"></i>
                                Users
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'org_list' %}">
                                <i class="fa fa-users"></i>
                                Organizations
                            </a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </nav>


            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                {% block content %}
                {% endblock %}
            </main>

        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

remote_manager/main/templates/main/dashboard.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
    </div>

    <div>
        <div class="row">
            <div class="col-6">
                <h5>Destination Host History</h5>
                <div id="host_chart" style="width:100%; height:280px;"></div>
            </div>
            <div class="col-6">
                <h5>Proxy Log:</h5>
                {% for l in conn_log %}
                <p class="">
                    {{ l }}
                </p>
                {% endfor %}
            </div>

        </div>

        <div class="row">
            <div class="col-6">
                <h5>User Access History</h5>
                <div id="user_chart" style="width:100%; height:280px;"></div>
            </div>
            <div class="col-6">
                <h5>User Log</h5>
                {% for l in user_log %}
                <p class="">
                    {{ l }}
                </p>
                {% endfor %}
            </div>
        </div>
    </div>





<script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.0.0/echarts.min.js"></script>
<script>
    var user_option = {
        title: {
            text: '',
            left: 'center'
        },
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b}: {c} ({d}%)'
        },
        legend: {
            top: '5%',
            left: 'center'
        },
        series: [
            {
                name: '',
                type: 'pie',
                radius: ['40%', '70%'],
                avoidLabelOverlap: false,
                itemStyle: {
                    borderRadius: 10,
                    borderColor: '#fff',
                    borderWidth: 2
                },
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                        show: true,
                        fontSize: '40',
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [
                    {% for u in user_count %}
                        {value: {{ u.1 }}, name: '{{ u.0 }}'},
                    {% endfor %}

                ]
            }
        ]
    }

    var host_option = {
        title: {
            text: '',
            left: 'center'
        },
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b}: {c} ({d}%)'
        },
        legend: {
            top: '5%',
            left: 'center'
        },
        series: [
            {
                name: '',
                type: 'pie',
                radius: ['40%', '70%'],
                avoidLabelOverlap: false,
                itemStyle: {
                    borderRadius: 10,
                    borderColor: '#fff',
                    borderWidth: 2
                },
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                        show: true,
                        fontSize: '40',
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [
                    {% for u in host_count %}
                        {value: {{ u.1 }}, name: '{{ u.0 }}'},
                    {% endfor %}

                ]
            }
        ]
    }



    var user_chart = echarts.init(document.getElementById('user_chart'))
    user_chart.setOption(user_option)
    var host_chart = echarts.init(document.getElementById('host_chart'))
    host_chart.setOption(host_option)
</script>
{% endblock %}

remote_manager/main/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Remote Managerβ</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body><div>
    <div class="align-middle">
        <h3 class="text-center pt-5">Remote Manager</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password">Password:</label><br>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

remote_manager/main/templates/main/org_detail.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">User Detail</h1>
        {{ organization.created_by }}
    </div>

    <div>
        <div class="my-2 text-right">
            <div class="btn-group">
                <a href="{% url 'org_update' organization.id %}" class="btn btn-primary" aria-current="page">Edit</a>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-4">
                    Name
                </div>
                <div class="col-8">
                    {{ organization.name }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Created by
                </div>
                <div class="col-8">
                    {{ organization.created_by }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Created at
                </div>
                <div class="col-8">
                    {{ organization.created_at }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Updated by
                </div>
                <div class="col-8">
                    {{ organization.updated_by }}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    Updated at
                </div>
                <div class="col-8">
                    {{ organization.updated_at }}
                </div>
            </div>
        </div>
    </div>



    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirm Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
                </div>
                <div class="modal-body">
                    Delete <b>{{ organization.name }}</b>?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" >Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

remote_manager/main/templates/main/org_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {% if request.path == '/org/create' %}
        <h1 class="h2">Add Organization</h1>
        {% else %}
        <h1 class="h2">Edit Organization</h1>
        {% endif %}
    </div>

    <div>
        <div>
            <form class="uniForm" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.name | as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

remote_manager/main/templates/main/org_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Organization List</h1>
    </div>

    <div>
        <div class="my-2 text-right">
            <a type="button" class="btn btn-primary" href="{% url 'org_create' %}">Add</a>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for org in organization_list %}
                <tr>
                    <th scope="row">{{ org.name }}</th>
                    <td>
                        <a href="{% url 'org_detail' org.id %}" class="btn btn-primary btn-sm" aria-current="page">Detail</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

remote_manager/main/templates/main/password.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Change "{{ request.user }}" Password</h1>
    </div>
    {% if messages %}
        {% for message in messages %}
            <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        {% endfor %}

    {% endif %}
    <div>
        <div>
            <form class="uniForm" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.old_password | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.new_password1 | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.new_password2 | as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

remote_manager/main/templates/main/user_form.html
{% extends 'main/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        {% if request.path == '/user/create' %}
        <h1 class="h2">Add User</h1>
        {% else %}
        <h1 class="h2">Edit User</h1>
        {% endif %}
    </div>

    <div>
        <div>
            <form class="uniForm" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password1 | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password2 | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.organization | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.is_staff | as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.is_active | as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

remote_manager/main/templates/main/user_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">User List</h1>
    </div>

    <div>
        <div class="my-2 text-right">
            <a type="button" class="btn btn-primary" href="{% url 'user_create' %}">Add</a>
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Username</th>
                    <th scope="col">Organization</th>
                    <th scope="col">Is Staff</th>
                    <th scope="col">Is Active</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for user in customuser_list %}
                <tr>
                    <th scope="row">{{ user.username }}</th>
                    <td>{{ user.organization }}</td>
                    <td>{{ user.is_staff }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>
                        <a href="{% url 'user_detail' user.id %}" class="btn btn-primary btn-sm" aria-current="page">Detail</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}